spring:
  application:
    name: blogify-api
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}
      database: blogify
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST:localhost}
server:
  forward-headers-strategy: framework
springdoc:
  swagger-ui:
    path: /swagger